# wallpaper {
#     monitor = HDMI-A-1
#     path = ~/Pictures/wallpapers/dracula/arch.png
#     fit_mode = cover
# }
#
# wallpaper {
#     monitor = DP-2
#     path = ~/Pictures/wallpapers/dracula/arch.png
#     fit_mode = cover
# }

wallpaper {
    monitor =
    path = ~/Pictures/wallpapers/dracula/arch.png
    fit_mode = cover
}
