# Dylen's Hyprland configuration
#
# Last major update on 1/6/26
# Defaults in any child configs will be commented out
# All config files (including this one) should reside in $XDG_CONFIG_HOME/hypr/ (e.g. ~/.config/hypr/)

source = ./programs.conf     # aliases (i.e. custom variables)
source = ./env.conf          # environment variables
source = ./monitors.conf
source = ./vars.conf         # hyprland variables (catch all)
source = ./windowrules.conf
source = ./workspaces.conf
source = ./perms.conf        # permission settings
source = ./binds.conf
source = ./init.conf         # autostart
