####################
### WINDOW RULES ###
####################

# See https://wiki.hypr.land/Configuring/Window-Rules/

# Init layout of startup
windowrule {
    name = term-layout
    match:class = kitty
    workspace = 2
    no_initial_focus = on
}

windowrule {
    name = firefox-layout
    match:class = firefox
    workspace = 3
    no_initial_focus = on
}

windowrule {
    name = slack-layout
    match:class = slack
    workspace = 1
    group = set lock always
    no_initial_focus = on
}

windowrule {
    name = spotify-layout
    match:class = spotify
    workspace = 1
    group = barred set
    move = 960x0
    no_initial_focus = on
}

windowrule {
    name = signal-layout
    match:class = signal
    workspace = 1
    group = invade
}

# Desktop app fixes
windowrule {
    name = zoom-menu-stabilize
    match:class = zoom
    match:title = menu window
    stay_focused = on
}

windowrule {
    name = zoom-toolbar-stabilize
    match:class = zoom
    match:title = Toolbar Menu
    stay_focused = on
}
